services:
  hls4ml:
    build: .
    command: /bin/bash
    depends_on:
      - xilinx
    environment:
      - DISPLAY
    image: hls4ml:forked
    init: true
    network_mode: host
    privileged: true
    volumes:
      - ./env:/home/hls4ml-user/env
      - ./work:/home/hls4ml-user/work
      - xilinx:/tools:rw

  xilinx:
    image: xilinx:18.04_2019.2
    volumes:
      - xilinx:/tools:rw

volumes:
  xilinx: {}
