CONDAPATH=/home/hls4ml-user/miniconda3
source ${CONDAPATH}/etc/profile.d/conda.sh

echo "Setting up X forwarding"
XAUTH=/home/hls4ml-user/env/.Xauthority
if test -f "$XAUTH"; then
    echo "Setting XAUTHORITY to $XAUTH"
    export XAUTHORITY=$XAUTH
else
    echo "File $XAUTH not found. Skipping X forwarding."
fi
