export XILINXD_LICENSE_FILE=/home/hls4ml-user/env/Xilinx.lic
export VIVADO_PATH=/tools/Xilinx/Vivado/2019.2
. ${VIVADO_PATH}/settings64.sh

export CPATH=/usr/include/x86_64-linux-gnu

echo "Setting up X forwarding"
XAUTH=/home/hls4ml-user/env/.Xauthority
if test -f "$XAUTH"; then
    echo "Setting XAUTHORITY to $XAUTH"
    export XAUTHORITY=$XAUTH
else
    echo "File $XAUTH not found. Skipping X forwarding."
fi
